name: Manually deploy docker

on:
  workflow_dispatch:

env:
  APP_JAVA_VERSION: 17
  DOCKER_MINER_IMAGE_NAME: mrcraftcod/channel-points-miner
  DOCKER_VIEWER_IMAGE_NAME: mrcraftcod/channel-points-miner-viewer

jobs:
  publish-miner:
    name: Publish Miner on DockerHub
    runs-on: ubuntu-latest
    concurrency: miner_docker
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.APP_JAVA_VERSION }}

      - name: Push branch/tag on Docker Hub
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            :miner:jib
            -DdockerUsername=${{ secrets.DOCKER_USERNAME }}
            -DdockerPassword=${{ secrets.DOCKER_TOKEN }}
            -Djib.to.image=${DOCKER_MINER_IMAGE_NAME}:${GITHUB_REF##*/}
      - name: Push latest on Docker Hub
        if: success() && github.ref == 'refs/heads/main'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            :miner:jib
            -DdockerUsername=${{ secrets.DOCKER_USERNAME }}
            -DdockerPassword=${{ secrets.DOCKER_TOKEN }}
            -Djib.to.image=${DOCKER_MINER_IMAGE_NAME}:latest

  publish-viewer:
    name: Publish Viewer on DockerHub
    runs-on: ubuntu-latest
    concurrency: viewer_docker
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.APP_JAVA_VERSION }}

      - name: Push branch/tag on Docker Hub
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            :viewer:jib
            -DdockerUsername=${{ secrets.DOCKER_USERNAME }}
            -DdockerPassword=${{ secrets.DOCKER_TOKEN }}
            -Djib.to.image=${DOCKER_VIEWER_IMAGE_NAME}:${GITHUB_REF##*/}
      - name: Push latest on Docker Hub
        if: success() && github.ref == 'refs/heads/main'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            :viewer:jib
            -DdockerUsername=${{ secrets.DOCKER_USERNAME }}
            -DdockerPassword=${{ secrets.DOCKER_TOKEN }}
            -Djib.to.image=${DOCKER_VIEWER_IMAGE_NAME}:latest
